import 'package:cloud_firestore/cloud_firestore.dart';

class UpdateAlimentosFunctions {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<void> updateAlimentos({
    required String id,
    required String nombreEsp,
    required String nombreEng,
    required String contenidoEsp,
    required String contenidoEng,
    required String video,
    required String calorias,
    required String proteina,
    required String porcion,
    required String gsaturadas,
    required String gMonoinsaturadas,
    required String gPoliinsaturadas,
    required String gHidrogenadas,
    required String grasa,
    required String carbohidrato,
    required String vitamina,
    required String fibra,
    required String azucar,
    required String sodio,
    required String categoryEsp,
    required String categoryEng,
    required String tipoEsp,
    required String tipoEng,
    required String tipoGrasaEsp,
    required String tipoGrasaEng,
    required String membershipEsp,
    required String membershipEng,
    required String imageUrl,
  }) async {
    await _firestore.collection('alimentos').doc(id).update({
      'NombreEsp': nombreEsp,
      'NombreEng': nombreEng,
      'ContenidoEsp': contenidoEsp,
      'ContenidoEng': contenidoEng,
      'Video': video,
      'Calorias': calorias,
      'Proteina': proteina,
      'Porcion': porcion,
      'GrasaSaturadas': gsaturadas,
      'GrasaMonoinsaturadas': gMonoinsaturadas,
      'GrasaPoliinsaturadas': gPoliinsaturadas,
      'GrasaHidrogenadas': gHidrogenadas,
      'Grasa': grasa,
      'Carbohidrato': carbohidrato,
      'Vitamina': vitamina,
      'Fibra': fibra,
      'Azucar': azucar,
      'Sodio': sodio,
      'CategoryEsp': categoryEsp,
      'CategoryEng': categoryEng,
      'TipoEsp': tipoEsp,
      'TipoEng': tipoEng,
      'TipoGrasaEsp': tipoGrasaEsp,
      'TipoGrasaEng': tipoGrasaEng,
      'MembershipEsp': membershipEsp,
      'MembershipEng': membershipEng,
      'Imagen': imageUrl,
    });
  }
}
